insert into autos(marca,submarca) values ('Ford','F150');
insert into autos(marca,submarca) values ('Ford','Ranger');
insert into autos(marca,submarca) values ('Ford','Mustang');
insert into autos(marca,submarca) values ('Ford','Ford E');
insert into autos(marca,submarca) values ('Ford','Cortina');
insert into autos(marca,submarca) values ('Ford','Country');
insert into autos(marca,submarca) values ('Ford','Escort');
insert into autos(marca,submarca) values ('Ford','Durango');
insert into autos(marca,submarca) values ('Ford','Del Rey');
insert into autos(marca,submarca) values ('Ford','Festiva');
insert into autos(marca,submarca) values ('Ford','Crown Victoria');
insert into autos(marca,submarca) values ('Ford','Cougar');
insert into autos(marca,submarca) values ('Ford','Fairmont');
insert into autos(marca,submarca) values ('Ford','Escort');
insert into autos(marca,submarca) values ('Ford','Sierra');
insert into autos(marca,submarca) values ('Ford','Galaxy');
insert into autos(marca,submarca) values ('Ford','Bronco');
insert into autos(marca,submarca) values ('Ford','Excursion');
insert into autos(marca,submarca) values ('Ford','Falcon');
insert into autos(marca,submarca) values ('Ford','Taurus');
insert into autos(marca,submarca) values ('Ford','Ka');
insert into autos(marca,submarca) values ('Ford','figo');
insert into autos(marca,submarca) values ('Ford','fusion');
insert into autos(marca,submarca) values ('Ford','ecosport');
insert into autos(marca,submarca) values ('Ford','edge');
insert into autos(marca,submarca) values ('Ford','explorer');
insert into autos(marca,submarca) values ('Ford','expedition');
insert into autos(marca,submarca) values ('Chevrolet','Astro');
insert into autos(marca,submarca) values ('Chevrolet','Beretta');
insert into autos(marca,submarca) values ('Chevrolet','Blazer');
insert into autos(marca,submarca) values ('Chevrolet','Camaro');
insert into autos(marca,submarca) values ('Chevrolet','Caprice');
insert into autos(marca,submarca) values ('Chevrolet','Cavalier');
insert into autos(marca,submarca) values ('Chevrolet','Celebrity');
insert into autos(marca,submarca) values ('Chevrolet','Chevelle');
insert into autos(marca,submarca) values ('Chevrolet','Citation');
insert into autos(marca,submarca) values ('Chevrolet','Corsica');
insert into autos(marca,submarca) values ('Chevrolet','Corvette');
insert into autos(marca,submarca) values ('Chevrolet','Elcamino');
insert into autos(marca,submarca) values ('Chevrolet','s10');
insert into autos(marca,submarca) values ('Chevrolet','Impala');
insert into autos(marca,submarca) values ('Chevrolet','Lumina');
insert into autos(marca,submarca) values ('Chevrolet','Lumina APV');
insert into autos(marca,submarca) values ('Chevrolet','Luv');
insert into autos(marca,submarca) values ('Chevrolet','Malibu');
insert into autos(marca,submarca) values ('Chevrolet','Monte Carlo');
insert into autos(marca,submarca) values ('Chevrolet','Nova');
insert into autos(marca,submarca) values ('Chevrolet','Chevy');
insert into autos(marca,submarca) values ('Chevrolet','Silverado');
insert into autos(marca,submarca) values ('Chevrolet','Suburban');
insert into autos(marca,submarca) values ('Chevrolet','Trax');
insert into autos(marca,submarca) values ('Chevrolet','Venture');
insert into autos(marca,submarca) values ('Chevrolet','beat');
insert into autos(marca,submarca) values ('Chevrolet','aveo');
insert into autos(marca,submarca) values ('Chevrolet','trax');
insert into autos(marca,submarca) values ('Chevrolet','equinox');
insert into autos(marca,submarca) values ('Chevrolet','traverse');
insert into autos(marca,submarca) values ('Chevrolet','tahoe');
insert into autos(marca,submarca) values ('Chevrolet','suburban');
insert into autos(marca,submarca) values ('Chevrolet','tornado');
insert into autos(marca,submarca) values ('Chevrolet','cheyenne');
insert into autos(marca,submarca) values ('Chevrolet','colorado');
insert into autos(marca,submarca) values ('Renault','18');
insert into autos(marca,submarca) values ('Renault','19');
insert into autos(marca,submarca) values ('Renault','20/30');
insert into autos(marca,submarca) values ('Renault','21');
insert into autos(marca,submarca) values ('Renault','clio');
insert into autos(marca,submarca) values ('Renault','Express');
insert into autos(marca,submarca) values ('Renault','fuego');
insert into autos(marca,submarca) values ('Renault','Kangoo');
insert into autos(marca,submarca) values ('Renault','Supercinco');
insert into autos(marca,submarca) values ('Renault','stepway');
insert into autos(marca,submarca) values ('Renault','duster');
insert into autos(marca,submarca) values ('Renault','captur');
insert into autos(marca,submarca) values ('Renault','koleos');
insert into autos(marca,submarca) values ('Renault','kwid');
insert into autos(marca,submarca) values ('Renault','oronch');
insert into autos(marca,submarca) values ('Renault','sandero');
insert into autos(marca,submarca) values ('Renault','twizy');
insert into autos(marca,submarca) values ('Renault','kangoo');
insert into autos(marca,submarca) values ('Chrysler','300');
insert into autos(marca,submarca) values ('Chrysler','Cirrus');
insert into autos(marca,submarca) values ('Chrysler','Concorde');
insert into autos(marca,submarca) values ('Chrysler','laser');
insert into autos(marca,submarca) values ('Chrysler','300');
insert into autos(marca,submarca) values ('Chrysler','pacifica');
insert into autos(marca,submarca) values ('Volkswagen','Vocho');
insert into autos(marca,submarca) values ('Volkswagen','Safari');
insert into autos(marca,submarca) values ('Volkswagen','Combi');
insert into autos(marca,submarca) values ('Volkswagen','Brasilia');
insert into autos(marca,submarca) values ('Volkswagen','T200');
insert into autos(marca,submarca) values ('Volkswagen','Caribe');
insert into autos(marca,submarca) values ('Volkswagen','Jetta');
insert into autos(marca,submarca) values ('Volkswagen','Corsar');
insert into autos(marca,submarca) values ('Volkswagen','Golf II');
insert into autos(marca,submarca) values ('Volkswagen','Derby');
insert into autos(marca,submarca) values ('Volkswagen','Polo');
insert into autos(marca,submarca) values ('Volkswagen','Pointer');
insert into autos(marca,submarca) values ('Volkswagen','Voyage');
insert into autos(marca,submarca) values ('Volkswagen','Golf II');
insert into autos(marca,submarca) values ('Volkswagen','polo');
insert into autos(marca,submarca) values ('Volkswagen','vento');
insert into autos(marca,submarca) values ('Volkswagen','virtus');
insert into autos(marca,submarca) values ('Volkswagen','tcross');
insert into autos(marca,submarca) values ('Volkswagen','tiguan');
insert into autos(marca,submarca) values ('Volkswagen','teramont');
insert into autos(marca,submarca) values ('Nissan','Lucino');
insert into autos(marca,submarca) values ('Nissan','Quest');
insert into autos(marca,submarca) values ('Nissan','Sentra');
insert into autos(marca,submarca) values ('Nissan','skyline');
insert into autos(marca,submarca) values ('Nissan','trade');
insert into autos(marca,submarca) values ('Nissan','tsuru');
insert into autos(marca,submarca) values ('Nissan','Vanettte');
insert into autos(marca,submarca) values ('Nissan','370z');
insert into autos(marca,submarca) values ('Nissan','altima');
insert into autos(marca,submarca) values ('Nissan','aramda');
insert into autos(marca,submarca) values ('Nissan','frontier');
insert into autos(marca,submarca) values ('Nissan','gt-r');
insert into autos(marca,submarca) values ('Nissan','kicks');
insert into autos(marca,submarca) values ('Nissan','leaf');
insert into autos(marca,submarca) values ('Nissan','march');
insert into autos(marca,submarca) values ('Nissan','maxima');
insert into autos(marca,submarca) values ('Nissan','np300');
insert into autos(marca,submarca) values ('Nissan','nv650');
insert into autos(marca,submarca) values ('Nissan','pathfinder');
insert into autos(marca,submarca) values ('Nissan','versa');
insert into autos(marca,submarca) values ('Nissan','v-drive');
insert into autos(marca,submarca) values ('Nissan','x-trail');
insert into autos(marca,submarca) values ('Nissan','murano');
insert into autos(marca,submarca) values ('Toyota','Land Cruiser');
insert into autos(marca,submarca) values ('Toyota','ae86');
insert into autos(marca,submarca) values ('Toyota','Starlet');
insert into autos(marca,submarca) values ('Toyota','mr2');
insert into autos(marca,submarca) values ('Toyota','cavalllier');
insert into autos(marca,submarca) values ('Toyota','yaris');
insert into autos(marca,submarca) values ('Toyota','corolla');
insert into autos(marca,submarca) values ('Toyota','camry');
insert into autos(marca,submarca) values ('Toyota','prius');
insert into autos(marca,submarca) values ('Toyota','rav4');
insert into autos(marca,submarca) values ('Toyota','avanza');
insert into autos(marca,submarca) values ('Toyota','c-hr');
insert into autos(marca,submarca) values ('Toyota','sienna');
insert into autos(marca,submarca) values ('Toyota','highlander');
insert into autos(marca,submarca) values ('Toyota','sequoia');
insert into autos(marca,submarca) values ('Mazda','626 MK4');
insert into autos(marca,submarca) values ('Mazda','626 MK5');
insert into autos(marca,submarca) values ('Mazda','626 MK6');
insert into autos(marca,submarca) values ('Mazda','sedan');
insert into autos(marca,submarca) values ('Mazda','cx-3');
insert into autos(marca,submarca) values ('Mazda','mx-5');
insert into autos(marca,submarca) values ('Mazda','cx-30');
insert into autos(marca,submarca) values ('Mazda','cx-9');
insert into autos(marca,submarca) values ('Mazda','mazda6');
insert into autos(marca,submarca) values ('Peugeot','204');
insert into autos(marca,submarca) values ('Peugeot','205');
insert into autos(marca,submarca) values ('Peugeot','205 t16');
insert into autos(marca,submarca) values ('Peugeot','206');
insert into autos(marca,submarca) values ('Peugeot','305');
insert into autos(marca,submarca) values ('Peugeot','309');
insert into autos(marca,submarca) values ('Peugeot','306');
insert into autos(marca,submarca) values ('Peugeot','405');
insert into autos(marca,submarca) values ('Peugeot','208');
insert into autos(marca,submarca) values ('Peugeot','2008');
insert into autos(marca,submarca) values ('Peugeot','301');
insert into autos(marca,submarca) values ('Peugeot','308');
insert into autos(marca,submarca) values ('Peugeot','3008');
insert into autos(marca,submarca) values ('Peugeot','5008');
insert into autos(marca,submarca) values ('Peugeot','rifter');
insert into autos(marca,submarca) values ('Peugeot','traveller');
insert into autos(marca,submarca) values ('Peugeot','landtrek');
insert into autos(marca,submarca) values ('Honda','quint');
insert into autos(marca,submarca) values ('Honda','Concerto');
insert into autos(marca,submarca) values ('Honda','civic');
insert into autos(marca,submarca) values ('Honda','accord');
insert into autos(marca,submarca) values ('Honda','insight');
insert into autos(marca,submarca) values ('Honda','city');
insert into autos(marca,submarca) values ('Honda','type r');
insert into autos(marca,submarca) values ('Honda','fit');
insert into autos(marca,submarca) values ('Honda','br-v');
insert into autos(marca,submarca) values ('Honda','hr-v');
insert into autos(marca,submarca) values ('Honda','cr-v');
insert into autos(marca,submarca) values ('Honda','pilot');
insert into autos(marca,submarca) values ('Honda','odyssey');
insert into autos(marca,submarca) values ('Seat','Ibiza 1');
insert into autos(marca,submarca) values ('Seat','leon');
insert into autos(marca,submarca) values ('Seat','arona');
insert into autos(marca,submarca) values ('Seat','ateca');
insert into autos(marca,submarca) values ('Seat','tarraco');
insert into autos(marca,submarca) values ('Cupra','ateca');
insert into autos(marca,submarca) values ('Cupra','leon');
insert into autos(marca,submarca) values ('Mercedes Benz','Clase c');
insert into autos(marca,submarca) values ('Mercedes Benz','Clase G');
insert into autos(marca,submarca) values ('Mercedes Benz','Clase S');
insert into autos(marca,submarca) values ('Mercedes Benz','MB 100');
insert into autos(marca,submarca) values ('Mercedes Benz','Andare');
insert into autos(marca,submarca) values ('Mercedes Benz','Multego');
insert into autos(marca,submarca) values ('Mercedes Benz','toreto');
insert into autos(marca,submarca) values ('Mercedes Benz','arggento');
insert into autos(marca,submarca) values ('Mercedes Benz','boxer');
insert into autos(marca,submarca) values ('Mercedes Benz','alliado');
insert into autos(marca,submarca) values ('Mercedes Benz','w201');
insert into autos(marca,submarca) values ('Mercedes Benz','GLA');
insert into autos(marca,submarca) values ('Mercedes Benz','GLB');
insert into autos(marca,submarca) values ('Mercedes Benz','GLC');
insert into autos(marca,submarca) values ('Mercedes Benz','GLE');
insert into autos(marca,submarca) values ('Mercedes Benz','maybatch');
insert into autos(marca,submarca) values ('Mercedes Benz','GLS');
insert into autos(marca,submarca) values ('Mercedes Benz','CLASE A');
insert into autos(marca,submarca) values ('Mercedes Benz','CLASE C');
insert into autos(marca,submarca) values ('Mercedes Benz','CLA');
insert into autos(marca,submarca) values ('Mercedes Benz','CLS');
insert into autos(marca,submarca) values ('Mercedes Benz','Clase 3');
insert into autos(marca,submarca) values ('Mercedes Benz','gt-4');
insert into autos(marca,submarca) values ('Mercedes Benz','clase v');
insert into autos(marca,submarca) values ('BMW','e28');
insert into autos(marca,submarca) values ('BMW','e30');
insert into autos(marca,submarca) values ('BMW','e23');
insert into autos(marca,submarca) values ('BMW','seire6');
insert into autos(marca,submarca) values ('BMW','serie 1');
insert into autos(marca,submarca) values ('BMW','serie 2');
insert into autos(marca,submarca) values ('BMW','serie 3');
insert into autos(marca,submarca) values ('BMW','serie 4');
insert into autos(marca,submarca) values ('BMW','serie 5');
insert into autos(marca,submarca) values ('BMW','serie 7');
insert into autos(marca,submarca) values ('BMW','serie 8');
insert into autos(marca,submarca) values ('BMW','x1');
insert into autos(marca,submarca) values ('BMW','x2');
insert into autos(marca,submarca) values ('BMW','x3');
insert into autos(marca,submarca) values ('BMW','x4');
insert into autos(marca,submarca) values ('BMW','x5');
insert into autos(marca,submarca) values ('BMW','x6');
insert into autos(marca,submarca) values ('BMW','x7');
insert into autos(marca,submarca) values ('BMW','z4');
insert into autos(marca,submarca) values ('BMW','m135');
insert into autos(marca,submarca) values ('BMW','m240');
insert into autos(marca,submarca) values ('BMW','m240');
insert into autos(marca,submarca) values ('BMW','m340');
insert into autos(marca,submarca) values ('BMW','m440');
insert into autos(marca,submarca) values ('BMW','m550');
insert into autos(marca,submarca) values ('BMW','m550');
insert into autos(marca,submarca) values ('BMW','m760');
insert into autos(marca,submarca) values ('BMW','seire8');
insert into autos(marca,submarca) values ('BMW','m8');
insert into autos(marca,submarca) values ('BMW','m35');
insert into autos(marca,submarca) values ('BMW','m40');
insert into autos(marca,submarca) values ('BMW','m50');
insert into autos(marca,submarca) values ('BMW','i3');
insert into autos(marca,submarca) values ('BMW','i8');
insert into autos(marca,submarca) values ('BMW','ix3');
insert into autos(marca,submarca) values ('Audi','100');
insert into autos(marca,submarca) values ('Audi','80');
insert into autos(marca,submarca) values ('Audi','5+5');
insert into autos(marca,submarca) values ('Audi','90');
insert into autos(marca,submarca) values ('Audi','coupe');
insert into autos(marca,submarca) values ('Audi','quattro');
insert into autos(marca,submarca) values ('Audi','80');
insert into autos(marca,submarca) values ('Audi','90');
insert into autos(marca,submarca) values ('Audi','v8');
insert into autos(marca,submarca) values ('Audi','a1');
insert into autos(marca,submarca) values ('Audi','a3');
insert into autos(marca,submarca) values ('Audi','a4');
insert into autos(marca,submarca) values ('Audi','a6');
insert into autos(marca,submarca) values ('Audi','a7');
insert into autos(marca,submarca) values ('Audi','a8');
insert into autos(marca,submarca) values ('Audi','q2');
insert into autos(marca,submarca) values ('Audi','q3');
insert into autos(marca,submarca) values ('Audi','q5');
insert into autos(marca,submarca) values ('Audi','q7');
insert into autos(marca,submarca) values ('Audi','q8');
insert into autos(marca,submarca) values ('Audi','r8');
insert into autos(marca,submarca) values ('Audi','tt');
insert into autos(marca,submarca) values ('Volvo','262');
insert into autos(marca,submarca) values ('Volvo','264');
insert into autos(marca,submarca) values ('Volvo','265');
insert into autos(marca,submarca) values ('Volvo','24');
insert into autos(marca,submarca) values ('Volvo','260');
insert into autos(marca,submarca) values ('Volvo','66');
insert into autos(marca,submarca) values ('Volvo','343');
insert into autos(marca,submarca) values ('Volvo','345');
insert into autos(marca,submarca) values ('Volvo','360');
insert into autos(marca,submarca) values ('Volvo','xc90');
insert into autos(marca,submarca) values ('Volvo','xc60');
insert into autos(marca,submarca) values ('Volvo','xc40');
insert into autos(marca,submarca) values ('Volvo','s60');
insert into autos(marca,submarca) values ('Porsche','911 carrera');
insert into autos(marca,submarca) values ('Porsche','9111sc');
insert into autos(marca,submarca) values ('Porsche','912e');
insert into autos(marca,submarca) values ('Porsche','911turbo');
insert into autos(marca,submarca) values ('Porsche','924');
insert into autos(marca,submarca) values ('Porsche','928');
insert into autos(marca,submarca) values ('Porsche','944');
insert into autos(marca,submarca) values ('Porsche','964');
insert into autos(marca,submarca) values ('Porsche','968');
insert into autos(marca,submarca) values ('Porsche','993');
insert into autos(marca,submarca) values ('Porsche','718');
insert into autos(marca,submarca) values ('Porsche','Panamera');
insert into autos(marca,submarca) values ('Porsche','Macan');
insert into autos(marca,submarca) values ('Porsche','Cayenne');
insert into autos(marca,submarca) values ('Kia','rio');
insert into autos(marca,submarca) values ('Kia','forte');
insert into autos(marca,submarca) values ('Kia','optima');
insert into autos(marca,submarca) values ('Kia','stinger');
insert into autos(marca,submarca) values ('Kia','soul');
insert into autos(marca,submarca) values ('Kia','seltos');
insert into autos(marca,submarca) values ('Kia','niro');
insert into autos(marca,submarca) values ('Kia','sportage');
insert into autos(marca,submarca) values ('Kia','sorento');
insert into autos(marca,submarca) values ('Kia','sedona');
insert into autos(marca,submarca) values ('Hyundai','grand i10');
insert into autos(marca,submarca) values ('Hyundai','accent');
insert into autos(marca,submarca) values ('Hyundai','elantra');
insert into autos(marca,submarca) values ('Hyundai','ioniq');
insert into autos(marca,submarca) values ('Hyundai','creta');
insert into autos(marca,submarca) values ('Hyundai','tucson');
insert into autos(marca,submarca) values ('Hyundai','santa fe');
insert into autos(marca,submarca) values ('Hyundai','santa fe 7');
insert into autos(marca,submarca) values ('Hyundai','starex');
insert into autos(marca,submarca) values ('Suzuki','ciaz');
insert into autos(marca,submarca) values ('Suzuki','ertiga');
insert into autos(marca,submarca) values ('Suzuki','ignis');
insert into autos(marca,submarca) values ('Suzuki','scross');
insert into autos(marca,submarca) values ('Suzuki','swift');
insert into autos(marca,submarca) values ('Suzuki','vitara');
insert into autos(marca,submarca) values ('Suzuki','ignis');
insert into autos(marca,submarca) values ('Mitsubishi','mirage');
insert into autos(marca,submarca) values ('Mitsubishi','eclise cross');
insert into autos(marca,submarca) values ('Mitsubishi','outlander');
insert into autos(marca,submarca) values ('Mitsubishi','montero sport');
insert into autos(marca,submarca) values ('Mitsubishi','l200');
insert into autos(marca,submarca) values ('Mitsubishi','outlander phev');
insert into autos(marca,submarca) values ('Fiat','mobi');
insert into autos(marca,submarca) values ('Fiat','uno');
insert into autos(marca,submarca) values ('Fiat','pailo adventure');
insert into autos(marca,submarca) values ('Fiat','fiat soul');
insert into autos(marca,submarca) values ('Fiat','ducato van cargo');
insert into autos(marca,submarca) values ('Mini','Mini hatch 3');
insert into autos(marca,submarca) values ('Mini','mini hatch 5');
insert into autos(marca,submarca) values ('Mini','mini convertible');
insert into autos(marca,submarca) values ('Mini','mini clubman');
insert into autos(marca,submarca) values ('Mini','mini countryman');
insert into autos(marca,submarca) values ('BAIC','x30');
insert into autos(marca,submarca) values ('BAIC','M50S');
insert into autos(marca,submarca) values ('BAIC','d20');
insert into autos(marca,submarca) values ('BAIC','x25');
insert into autos(marca,submarca) values ('BAIC','x35');
insert into autos(marca,submarca) values ('BAIC','x65');
insert into autos(marca,submarca) values ('BAIC','bj20');
insert into autos(marca,submarca) values ('BAIC','bj40');
insert into autos(marca,submarca) values ('BAIC','vigus3');
insert into autos(marca,submarca) values ('JAC','J4');
insert into autos(marca,submarca) values ('JAC','SEi1');
insert into autos(marca,submarca) values ('JAC','SEI2');
insert into autos(marca,submarca) values ('JAC','SEI3');
insert into autos(marca,submarca) values ('JAC','SEI4');
insert into autos(marca,submarca) values ('JAC','SEi7');
insert into autos(marca,submarca) values ('JAC','Frison T6');
insert into autos(marca,submarca) values ('JAC','Frison T8');
insert into autos(marca,submarca) values ('JAC','x200');
insert into autos(marca,submarca) values ('Acura','ILX');
insert into autos(marca,submarca) values ('Acura','RDX');
insert into autos(marca,submarca) values ('Acura','MDX');
insert into autos(marca,submarca) values ('Acura','TLX');
insert into autos(marca,submarca) values ('Acura','NSX');
insert into autos(marca,submarca) values ('Lincoln','MKZ');
insert into autos(marca,submarca) values ('Lincoln','mkz hib');
insert into autos(marca,submarca) values ('Lincoln','Corsair');
insert into autos(marca,submarca) values ('Lincoln','Nautilus');
insert into autos(marca,submarca) values ('Lincoln','COntinental');
insert into autos(marca,submarca) values ('Lincoln','Aviator');
insert into autos(marca,submarca) values ('Lincoln','Navigartor');
insert into autos(marca,submarca) values ('Land Rover','range rover');
insert into autos(marca,submarca) values ('Land Rover','range rover sport');
insert into autos(marca,submarca) values ('Land Rover','range rover velar');
insert into autos(marca,submarca) values ('Land Rover','range rover evoque');
insert into autos(marca,submarca) values ('Land Rover','discovery');
insert into autos(marca,submarca) values ('Land Rover','defender');
insert into autos(marca,submarca) values ('Infiniti','q50');
insert into autos(marca,submarca) values ('Infiniti','q60');
insert into autos(marca,submarca) values ('Infiniti','qx30');
insert into autos(marca,submarca) values ('Infiniti','qx50');
insert into autos(marca,submarca) values ('Infiniti','qdx60');
insert into autos(marca,submarca) values ('Infiniti','qx70');
insert into autos(marca,submarca) values ('Infiniti','qx80');
insert into autos(marca,submarca) values ('Infiniti','qx hybrid');
insert into autos(marca,submarca) values ('Infiniti','q60 hybrid');
insert into autos(marca,submarca) values ('Subaru','xv');
insert into autos(marca,submarca) values ('Subaru','foerster');
insert into autos(marca,submarca) values ('Subaru','wrx/STi');
insert into autos(marca,submarca) values ('Subaru','BRZ');
insert into autos(marca,submarca) values ('Jaguar','f-pace');
insert into autos(marca,submarca) values ('Jaguar','e-pace');
insert into autos(marca,submarca) values ('Jaguar','i-pace');
insert into autos(marca,submarca) values ('Jaguar','f-tyupe');
insert into autos(marca,submarca) values ('Jaguar','xe');
insert into autos(marca,submarca) values ('Jaguar','xf');
insert into autos(marca,submarca) values ('Alfa Romeo','giulietta');
insert into autos(marca,submarca) values ('Alfa Romeo','giulia');
insert into autos(marca,submarca) values ('Alfa Romeo','stelvio');
insert into autos(marca,submarca) values ('Smart','forfour');
insert into autos(marca,submarca) values ('Smart','fortwo');
insert into autos(marca,submarca) values ('Jeep','cherokee');
insert into autos(marca,submarca) values ('Jeep','compass');
insert into autos(marca,submarca) values ('Jeep','renegade');
insert into autos(marca,submarca) values ('Jeep','gladiator');
insert into autos(marca,submarca) values ('Jeep','wrangler');