INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Álvaro Obregón','Patricio Ruiz Idania','Patricio Ruiz Idania','AOB-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Álvaro Obregón','Clairin Guillen Adriana','Clairin Guillen Adriana','AOB-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Álvaro Obregón','Tejeda Morales Ana Cecilia','Tejeda Morales Ana Cecilia','AOB-3');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Álvaro Obregón','Ruiz Córdova Daisy Dayan','Ruiz Córdova Daisy Dayan','AOB-4');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Azcapotzalco','Ojeda Lara Beatriz','Ojeda Lara Beatriz','AZC-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Azcapotzalco','Almeida Suarez Aida','Almeida Suarez Aida','AZC-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Azcapotzalco','Cedillo Lara Mary Carmen','Cedillo Lara Mary Carmen','AZC-3');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Azcapotzalco','Ana Gloria Lagunas Martínez','Ana Gloria Lagunas Martínez','AZC-4');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Benito Juárez','Castillo Romero Ana Lilia','Castillo Romero Ana Lilia','BJU-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Benito Juárez','Alatorre Campos Mayra Bárbara','Alatorre Campos Mayra Bárbara','BJU-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Benito Juárez','Leal Velázquez Karla','Leal Velázquez Karla','BJU-3');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Benito Juárez','Carrillo Castillo Violeta','Carrillo Castillo Violeta','BJU-4');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Benito Juárez','Ruiz Canizales Lorena','Ruiz Canizales Lorena','BJU-5');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Coyoacán','Vázquez Mora Yazmin','Vázquez Mora Yazmin','COY-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Coyoacán','Pérez Pérez Ingrid Thalía','Pérez Pérez Ingrid Thalía','COY-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Coyoacán','Peña Grimaldo América Genoveva','Peña Grimaldo América Genoveva','COY-3');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Coyoacán','Cazares Covarrubias Gladis Del Carmen','Cazares Covarrubias Gladis Del Carmen','COY-4');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Coyoacán','Camacho Escobar Sandra','Camacho Escobar Sandra','COY-5');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuauhtémoc','Gómez Soto Jazmín','Gómez Soto Jazmín','CUH-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuauhtémoc','Aguilar Herrera Norma','Aguilar Herrera Norma','CUH-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuauhtémoc','Velázquez Vázquez Cynthia Joanna','Velázquez Vázquez Cynthia Joanna','CUH-3');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuauhtémoc','Herrera Martínez Leticia','Herrera Martínez Leticia','CUH-4');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuauhtémoc','Navarrete Salazar Liliana','Navarrete Salazar Liliana','CUH-5');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuauhtémoc','Roche García Maria Eugenia','Roche García Maria Eugenia','CUH-6');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuauhtémoc','Tapia Martínez Loreto Virginia','Tapia Martínez Loreto Virginia','CUH-7');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuauhtémoc','López Leyva María del Carmen','López Leyva María del Carmen','CUH-8');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuajimalpa','Mejía Padilla Diana','Mejía Padilla Diana','CUJ-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuajimalpa','Gómez Cruz Victoria Edith','Gómez Cruz Victoria Edith','CUJ-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Gustavo A. Madero','Hernández García Rubí Fabiola','Hernández García Rubí Fabiola','GAM-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Gustavo A. Madero','Balderas Islas Martha Evangelina','Balderas Islas Martha Evangelina','GAM-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Gustavo A. Madero','González García Elvira','González García Elvira','GAM-3');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Gustavo A. Madero','Rodríguez López Gabriela','Rodríguez López Gabriela','GAM-4');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Gustavo A. Madero','Castillo Viveros Yanet','Castillo Viveros Yanet','GAM-5');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Gustavo A. Madero','Osorio Cruz Leticia','Osorio Cruz Leticia','GAM-6');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Gustavo A. Madero','Carreón Méndez Eréndira','Carreón Méndez Eréndira','GAM-7');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Gustavo A. Madero','Mendoza Del Barrio Patricia Guadalupe','Mendoza Del Barrio Patricia Guadalupe','GAM-8');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztacalco','Posada Martínez Dulce María','Posada Martínez Dulce María','IZC-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztacalco','García Ruiz María Guadalupe','García Ruiz María Guadalupe','IZC-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztacalco','Amezquita Rescalvo Claudia','Amezquita Rescalvo Claudia','IZC-3');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztapalapa','Vázquez Zúñiga Marlenee','Vázquez Zúñiga Marlenee','IZP-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztapalapa','Zarate Reynoso María de la Luz','Zarate Reynoso María de la Luz','IZP-10');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztapalapa','García Olguín Paulina Marisela','García Olguín Paulina Marisela','IZP-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztapalapa','Palacios Alejo Irma','Palacios Alejo Irma','IZP-4');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztapalapa','Hernández Hernández Fabiola','Hernández Hernández Fabiola','IZP-5');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztapalapa','Silva Carranza María Guadalupe','Silva Carranza María Guadalupe','IZP-6');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztapalapa','Hernández Martínez Lizett Denisse','Hernández Martínez Lizett Denisse','IZP-7');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztapalapa','Hidalgo Rangel María Verónica','Hidalgo Rangel María Verónica','IZP-8');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztapalapa','Pantoja Pérez Laura Alicia','Pantoja Pérez Laura Alicia','IZP-9');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('La Magdalena Contreras','González Ruiz Mayra Isabel','González Ruiz Mayra Isabel','MAC-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('La Magdalena Contreras','Olmos Hernández María Viviana','Olmos Hernández María Viviana','MAC-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Miguel Hidalgo','Vázquez Roa Yessica Fabiola','Vázquez Roa Yessica Fabiola','MIH-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Miguel Hidalgo','Roldan Gutiérrez Ana Lidia','Roldan Gutiérrez Ana Lidia','MIH-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Miguel Hidalgo','Ávila Campos María Del Consuelo','Ávila Campos María Del Consuelo','MIH-3');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Miguel Hidalgo','Murcia Pinedo Grace Montserrat','Murcia Pinedo Grace Montserrat','MIH-4');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Miguel Hidalgo','Fuentes Hernández Jessica Victoria','Fuentes Hernández Jessica Victoria','MIH-5');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Milpa Alta','Martínez Rojas María Eugenia','Martínez Rojas María Eugenia','MIL-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Milpa Alta','Ramírez Caldiño Laura Angélica','Ramírez Caldiño Laura Angélica','MIL-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Tláhuac','Ortiz Piña María Guadalupe','Ortiz Piña María Guadalupe','TLH-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Tláhuac','Arredondo Amado Idaly','Arredondo Amado Idaly','TLH-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Tlalpan','Mondragón Guzmán Esthela','Mondragón Guzmán Esthela','TLP-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Tlalpan','Haro Jiménez Leticia','Haro Jiménez Leticia','TLP-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Tlalpan','Galicia Delgado Ana María','Galicia Delgado Ana María','TLP-3');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Tlalpan','Cordero Meza Juana','Cordero Meza Juana','TLP-4');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Venustiano Carranza','Rincón Cabrera María de los Ángeles','Rincón Cabrera María de los Ángeles','VCA-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Venustiano Carranza','Mayra Citlali Cedillo Sanchez','Mayra Citlali Cedillo Sanchez','VCA-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Venustiano Carranza','Martínez Rivera Erika Juana','Martínez Rivera Erika Juana','VCA-3');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Venustiano Carranza','Becerril Estrada Seltzin Samara','Becerril Estrada Seltzin Samara','VCA-4');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Venustiano Carranza','Carreto Osorio Rocio Elba','Carreto Osorio Rocio Elba','VCA-5');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Xochimilco','Reza Rosas María Fabiola','Reza Rosas María Fabiola','XOC-1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Xochimilco','Enciso Sabino Isabel','Enciso Sabino Isabel','XOC-2');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Álvaro Obregón','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Azcapotzalco','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Benito Juárez','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Coyoacán','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuauhtémoc','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Cuajimalpa','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Gustavo A. Madero','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztacalco','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Iztapalapa','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('La Magdalena Contreras','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Miguel Hidalgo','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Milpa Alta','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Tláhuac','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Tlalpan','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Venustiano Carranza','administrador','administrador','1');
INSERT INTO datos (alcaldia, equipo, coordinador,usuario) VALUES ('Xochimilco','administrador','administrador','1');
